### ISSUE TITLE
Final prep task list

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41035#9]
- [x] Setup a google drive folder and share
- [x] Setup a roster in gdrive
- [x] Finalize the schedule
- [x] Setup meeting with John, Dijana, Jan for final details
- [x] ~~Setup an email list for the course??~~ Use Teams to send info
- [x] [May 21] Email all lecturers reminding them about their lecture time and ask if they need any thing
- [x] Test MS teams features with Jan
- [x] Setup the video service and email out the url for the lectures, office hours, assignment intros, etc.
- [x] Ask Dijana to handle the lecturer consent and youtube posting
- [x] Setup the TA with their tasks
- [x] Review all past assignment work
- [x] Write up assignments on the website
- [x] Develop assessment on intermediate assignments
- [x] [May 24] Email a welcome message and reminder to all students
- [x] Provide the lecture url(s) to all coordinators so that non-registered students can join the lectures
- [ ] Ask for short bio from the lecturers?
- [x] Update my personal calendar with all of the course activities
- [x] Cancel/reschedule conflicting meetings
  - [x] Meeting with Frans/Arend
  - [x] Bicycle lab meeting
  - [x] Marco/Leila meeting 
  - [x] Language course on June 11
  - [x] Meeting with Max
  - [x] Multi-body B lectures
- [x] Feedback at end of course
- [x] Add some explanation about MS teams to the course website
- [x] Provide MS Teams instructions to the lecturers
- [x] Prize for pub quiz
- [x] Prize for best prediction (golden bell?)
- [x] Schedule meetings in teams for each lecture, OH, social
- [x] Create introduction slides for first day
